ozark/pom.xml
ozark/src/main/java/org/glassfish/ozark/binding/BindingResultImpl.java
ozark/src/main/java/org/glassfish/ozark/binding/BindingResultUtils.java
ozark/src/main/java/org/glassfish/ozark/binding/ConstraintViolationUtils.java
ozark/src/main/java/org/glassfish/ozark/binding/ValidationErrorImpl.java
ozark/src/test/java/org/glassfish/ozark/binding/ConstraintViolationUtilsTest.java
test/pom.xml
test/validation/src/main/java/org/glassfish/ozark/test/validation/ErrorDataBean.java
test/validation/src/main/java/org/glassfish/ozark/test/validation/FormController.java
test/validation/src/main/java/org/glassfish/ozark/test/validation/FormControllerProperty.java
test/validation/src/main/webapp/WEB-INF/views/binderror.jsp
test/validation/src/main/webapp/WEB-INF/views/error.jsp
test/validation/src/test/java/org/glassfish/ozark/test/validation/ValidationIT.java

This PR contains the required changes for Ozark to support the new `ValidationError` interface and the modified `BindingResult`.
Please note the current version of the implementation doesn't yet set the parameter name correctly. This has to be done in a later step. But IMO that's ok for now as currently Ozark also doesn't know about the parameter name and therefore even doesn't implement `BindingResult.getViolation(String)` at all.

MVC_SPEC-59 Added support for new ValidationError API

---

ozark/pom.xml
ozark/src/test/java/org/glassfish/ozark/core/ViewableWriterTest.java
ozark/src/test/java/org/glassfish/ozark/util/AnnotationUtilsTest.java
ozark/src/test/resources/META-INF/beans.xml
ozark/src/test/resources/logging.properties

Resolves [OZARK-81](https://java.net/jira/browse/OZARK-81).

OZARK-81: Replacing CDI-Unit with Deltaspike Test-Control

---

.travis-build.sh
.travis.yml

I updated the Glassfish version to use for the integration tests to the latest promoted build of Glassfish 5. Looking forward to see whether the integration tests still pass. ;-)

Use latest promoted Glassfish 5 build for integration tests

---

ext/jade/pom.xml
test/jade/src/main/java/org/glassfish/ozark/test/jade/DummyFilter.java

Minor commit to allow usage of some newer jade4j features. 
This will also remove the need to manually exclude old version of jade4j from ozark-jade extension dependency and adding a new one explicitly for users who want to use newer jade4j features.

updated jade4j to 1.2.5 version

---

pom.xml

This PR updates Jersey to the latest version. This is especially important, because this Jersey version fixes the following issue:
https://github.com/jersey/jersey/issues/3582

Updating Jersey to 2.26-b07

---

.travis.yml

Back to an older Glassfish 5 build which doesn't break `BindingInterceptorImpl`...

Back to older Glassfish 5 nightly

---

.travis.yml

I removed a command which basically fetched the latest mvc-api snaphots from the old java.net Maven repo. I don't think that this is necessary any more, because Travis already supports the Sonatype snapshots repo.

Removed dependency:get from travis build

---

ozark/src/main/java/org/glassfish/ozark/MvcContextImpl.java
ozark/src/main/java/org/glassfish/ozark/cdi/OzarkCdiExtension.java
ozark/src/main/java/org/glassfish/ozark/uri/ApplicationUris.java
ozark/src/main/java/org/glassfish/ozark/uri/DefaultMvcUriBuilder.java
ozark/src/main/java/org/glassfish/ozark/uri/UriTemplate.java
ozark/src/main/java/org/glassfish/ozark/uri/UriTemplateParser.java
ozark/src/main/java/org/glassfish/ozark/util/AnnotationUtils.java
ozark/src/main/java/org/glassfish/ozark/util/BeanUtils.java
ozark/src/main/java/org/glassfish/ozark/util/ControllerUtils.java
ozark/src/test/java/org/glassfish/ozark/uri/ApplicationUrisTest.java
ozark/src/test/java/org/glassfish/ozark/uri/DefaultMvcUriBuilderTest.java
ozark/src/test/java/org/glassfish/ozark/uri/UriBuilderTestControllers.java
ozark/src/test/java/org/glassfish/ozark/uri/UriTemplateParserTest.java
ozark/src/test/java/org/glassfish/ozark/util/BeanUtilsTest.java
ozark/src/test/java/org/glassfish/ozark/util/CdiUtilsTest.java
ozark/src/test/java/org/glassfish/ozark/util/ControllerUtilsTest.java
test/pom.xml
test/uri-builder/pom.xml
test/uri-builder/src/main/java/org/glassfish/ozark/test/uribuilder/ParameterController.java
test/uri-builder/src/main/java/org/glassfish/ozark/test/uribuilder/UriBuilderApplication.java
test/uri-builder/src/main/java/org/glassfish/ozark/test/uribuilder/UriBuilderController.java
test/uri-builder/src/main/webapp/WEB-INF/beans.xml
test/uri-builder/src/main/webapp/WEB-INF/views/uri-builder.jsp
test/uri-builder/src/main/webapp/index.html
test/uri-builder/src/main/webapp/ozark.css
test/uri-builder/src/test/java/org/glassfish/ozark/test/uribuilder/MvcUriBuilderIT.java

Implementation of [MvcUriBuilder][1]. 
Following method of `MvcContext` is still not implemented:
```URI uri(String identifier, List<Object> params);```
Reason is that method overloading is not supported by EL. This is the reason why one of the integration tests is failing. 
I started a [discussion in the mailing list][2] if we should drop this method.
[1]: https://github.com/mvc-spec/mvc-spec/blob/master/api/src/main/java/javax/mvc/MvcUriBuilder.java
[2]: https://groups.google.com/forum/#!topic/jsr371-users/VU2BitCkJsQ

Implement MvcUriBuilder

---

core/pom.xml
core/src/main/java/org/mvcspec/ozark/bootstrap/OzarkCoreFeature.java
core/src/main/java/org/mvcspec/ozark/bootstrap/OzarkInitializer.java
core/src/main/java/org/mvcspec/ozark/servlet/OzarkContainerInitializer.java
core/src/main/java/org/mvcspec/ozark/util/AnnotationUtils.java
jersey/src/main/java/org/mvcspec/ozark/jersey/bootstrap/OzarkJerseyFeature.java

In this PR fixed problem with `OzarkFeature` when it not works properly in RESTEasy case. Issue was that RESTEasy return in `config` object only classes from sub-packages `org.jboss.resteasy`. It means that implementation provide only own classes there. I found proper way how to deal with this using `ServletContext`.
Additionally extended Manifest to provide implementation version information.

Controller detection doesn't work on RESTEasy

---

.travis/tests.sh
test/pom.xml

Switched to latest version of glassfish 5.0.1 for verifying a bug-fix.
http://download.oracle.com/glassfish/5.0.1/nightly/latest-web.zip

Enabled asciidoc tests for Glassfish 5.0 #134

---

core/src/main/java/org/mvcspec/ozark/core/ViewableWriter.java
core/src/main/java/org/mvcspec/ozark/engine/ServletViewEngine.java
core/src/main/java/org/mvcspec/ozark/engine/ViewEngineBase.java
core/src/main/java/org/mvcspec/ozark/engine/ViewEngineContextImpl.java
core/src/test/java/org/mvcspec/ozark/engine/ViewEngineContextImplTest.java
ext/asciidoc/src/main/java/org/mvcspec/ozark/ext/asciidoc/AsciiDocViewEngine.java
ext/freemarker/src/main/java/org/mvcspec/ozark/ext/freemarker/FreemarkerViewEngine.java
ext/handlebars/src/main/java/org/mvcspec/ozark/ext/handlebars/HandlebarsViewEngine.java
ext/jade/src/main/java/org/mvcspec/ozark/ext/jade/JadeViewEngine.java
ext/jetbrick/src/main/java/org/mvcspec/ozark/ext/jetbrick/JetbrickViewEngine.java
ext/jsr223/src/main/java/org/mvcspec/ozark/ext/jsr223/Jsr223ViewEngine.java
ext/mustache/src/main/java/org/mvcspec/ozark/ext/mustache/MustacheViewEngine.java
ext/pebble/src/main/java/org/mvcspec/ozark/ext/pebble/PebbleViewEngine.java
ext/stringtemplate/src/main/java/org/mvcspec/ozark/ext/stringtemplate/StringTemplateViewEngine.java
ext/thymeleaf/src/main/java/org/mvcspec/ozark/ext/thymeleaf/ThymeleafViewEngine.java
ext/velocity/src/main/java/org/mvcspec/ozark/ext/velocity/VelocityViewEngine.java

This pull request contains the required changes to support the new `ViewEngineContext` methods which were part of mvc-spec/mvc-spec#132.
I'll merge this today. Just want check if all the tests run fine. ;-)

Removed Servlet API dependency from MVC API

---

core/pom.xml
core/src/main/java/org/mvcspec/ozark/cdi/OzarkCdiExtension.java
core/src/main/java/org/mvcspec/ozark/cdi/types/AnnotatedMethodWrapper.java
core/src/main/java/org/mvcspec/ozark/cdi/types/AnnotatedTypeProcessor.java
jersey/src/main/java/org/mvcspec/ozark/jersey/bootstrap/JerseyConfigProvider.java
jersey/src/main/java/org/mvcspec/ozark/jersey/validation/OzarkValidationInterceptor.java

This pull request will add a custom `ValidationInterceptor` to the Jersey module which will prevent Jersey from performing validation for MVC requests.
Unfortunately this still isn't enough to get rid of the `@ValidateOnExecution(NONE)` requirement because now the Hibernate Validation CDI interceptor will perform the validation. So by default Jersey actually performs manual validation of BV constraints before the Hibernate Validator CDI interceptor gets invoked, so the latter one will never fail because Jersey will abort processing before.
The good news is that if find a solution for the Hibernate Validation interceptor, we won't need  `@ValidateOnExecution(NONE)` for both Jersey and RESTEasy. And that would be AWESOME!
Travis CI, test please! ;-)

Force Jersey to skip validation for MVC controllers

---

resteasy/pom.xml
resteasy/src/main/java/org/mvcspec/ozark/resteasy/bootstrap/RestEasyConfigProvider.java
resteasy/src/main/java/org/mvcspec/ozark/resteasy/validation/OzarkGeneralValidator.java
resteasy/src/main/java/org/mvcspec/ozark/resteasy/validation/OzarkValidationResolver.java
resteasy/src/main/resources/META-INF/services/org.mvcspec.ozark.bootstrap.ConfigProvider

This pull request will disable the RESTEasy validation for MVC controllers. There are still some TODOs, but it is basically working fine. This means that you won't need `@ValidateOnExecution(NONE)` any more on Wildfly and Tomcat with RESTEasy.

Skip RESTEasy validation for MVC controllers

---

core/src/main/java/org/mvcspec/ozark/core/ViewResponseFilter.java
test/annotations/src/test/java/org/mvcspec/ozark/test/annotations/AnnotationsIT.java

Ozark currently fails checking for the `void` return type. This one came up while working on the TCK.
Travis, check please!

Fixed check for 'void' return type

---

ext/jtwig/pom.xml
ext/jtwig/src/main/java/org/mvcspec/ozark/ext/jtwig/JtwigViewEngine.java
ext/jtwig/src/main/resources/META-INF/beans.xml
ext/pom.xml
test/jtwig/pom.xml
test/jtwig/src/main/java/org/mvcspec/ozark/test/jtwig/HelloController.java
test/jtwig/src/main/java/org/mvcspec/ozark/test/jtwig/MyApplication.java
test/jtwig/src/main/webapp/WEB-INF/beans.xml
test/jtwig/src/main/webapp/WEB-INF/views/hello.twig.html
test/jtwig/src/main/webapp/index.html
test/jtwig/src/main/webapp/ozark.css
test/jtwig/src/test/java/org/mvcspec/ozark/test/jtwig/JtwigIT.java
test/pom.xml

-  add a new View Engine -> [Jtwig](http://jtwig.org/)
Jtwig is a template engine for Java based on Twig for PHP, which is also based on Django template engine (Python).
[doc - reference](http://jtwig.org/documentation/reference)
license Apache .

Jtwig-ViewEngine.

---

ext/thymeleaf/src/main/java/org/mvcspec/ozark/ext/thymeleaf/CDIWebContext.java
ext/thymeleaf/src/main/java/org/mvcspec/ozark/ext/thymeleaf/ThymeleafViewEngine.java
test/thymeleaf/src/main/java/org/mvcspec/ozark/test/thymeleaf/Greeting.java
test/thymeleaf/src/main/webapp/WEB-INF/views/hello.html

This adds support for `@Named`-Annotated beans in Thymeleaf.
At first I tried extending the WebContext, but that doesn't work as most of it's methods are final.
The Context enumerates all named beans upon constructions, which should be a fairly cheap operation. Initialization is delayed until the reference is actually used in the template. The original idea for this came from https://github.com/inbuss/thymeleaf-cdi, so @inbuss should get the credit for it. 
About testing: I haven't seen any test in the ext package, so I'm not sure how to approach this. Do you have any plans for this?
Closes #64

resolve cdi-named-beans in thymeleaf

---

core/src/main/java/org/mvcspec/ozark/engine/FaceletsViewEngine.java
core/src/main/java/org/mvcspec/ozark/engine/JspViewEngine.java
core/src/main/java/org/mvcspec/ozark/engine/ViewEngineFinder.java
ext/asciidoc/src/main/java/org/mvcspec/ozark/ext/asciidoc/AsciiDocViewEngine.java
ext/freemarker/src/main/java/org/mvcspec/ozark/ext/freemarker/FreemarkerViewEngine.java
ext/groovy/src/main/java/org/mvcspec/ozark/ext/groovy/GroovyViewEngine.java
ext/handlebars/src/main/java/org/mvcspec/ozark/ext/handlebars/HandlebarsViewEngine.java
ext/jade/src/main/java/org/mvcspec/ozark/ext/jade/JadeViewEngine.java
ext/jetbrick/src/main/java/org/mvcspec/ozark/ext/jetbrick/JetbrickViewEngine.java
ext/jsr223/src/main/java/org/mvcspec/ozark/ext/jsr223/Jsr223ViewEngine.java
ext/jtwig/src/main/java/org/mvcspec/ozark/ext/jtwig/JtwigViewEngine.java
ext/mustache/src/main/java/org/mvcspec/ozark/ext/mustache/MustacheViewEngine.java
ext/pebble/src/main/java/org/mvcspec/ozark/ext/pebble/PebbleViewEngine.java
ext/stringtemplate/src/main/java/org/mvcspec/ozark/ext/stringtemplate/StringTemplateViewEngine.java
ext/thymeleaf/src/main/java/org/mvcspec/ozark/ext/thymeleaf/ThymeleafViewEngine.java
ext/velocity/src/main/java/org/mvcspec/ozark/ext/velocity/VelocityViewEngine.java

This PR contains the required changes for Ozark to support the new `ViewEngine` constants. It contains the following changes.
* Use PRIORITY_BUILTIN for the default view engines
* Use PRIORITY_FRAMEWORK for all extension view engines
* Assume PRIORITY_APPLICATION if no `@Priority` annotation is found.
Please do not merge this yet, because we have to wait for mvc-spec/mvc-spec#191 to get merged before.

Updated Ozark regarding new ViewEngine constants

---

.travis/tests.sh

upgrade to the latest version of Wildfly with full support for Java EE 8.
http://wildfly.org/news/2018/08/30/WildFly14-Final-Released/

update for Wildfly-14

---

.travis/tests.sh

Looks like the builds are currently failing, because we cannot download Glassfish. This seems to be caused by curl not following redirects by default. This PR fixes this. Let's see if the tests pass now.

All curl calls should follow redirects

---

.travis/tests.sh

This PR contains some updates for the servers we run our tests against:
* Glassfish 5.0.1 nightly -> Eclipse Glassfish 5.1.0.RC1
* Wildfly 14.0.0 -> Wildfly 14.0.1
* Liberty 18.0.0.2 -> Liberty 18.0.0.3 
Let's see if Travis likes it. :-)

Updated server versions for integration tests

---

.travis.yml

I'm currently working on the TCK tests for the MVC CDI event support and discovered there are quite some edge cases we don't support correctly.
My plan is to first finish all the TCK tests and then to fix the failures in Ozark. Therefore, I'll allow TCK failures for the Ozark build for a some time.

Allow TCK failures for now
