ozark/pom.xml
ozark/src/main/java/org/glassfish/ozark/MvcAppConfig.java
ozark/src/main/java/org/glassfish/ozark/jersey/OzarkFeature.java
ozark/src/main/java/org/glassfish/ozark/locale/DefaultLocaleResolver.java
ozark/src/main/java/org/glassfish/ozark/locale/LocaleRequestFilter.java
ozark/src/main/java/org/glassfish/ozark/locale/LocaleResolverChain.java
ozark/src/main/java/org/glassfish/ozark/locale/LocaleResolverContextImpl.java
ozark/src/main/java/org/glassfish/ozark/servlet/OzarkContainerInitializer.java
test/locale/pom.xml
test/locale/src/main/java/org/glassfish/ozark/test/locale/LocaleController.java
test/locale/src/main/java/org/glassfish/ozark/test/locale/MyApplication.java
test/locale/src/main/java/org/glassfish/ozark/test/locale/QueryLocaleResolver.java
test/locale/src/main/resources/LICENSE.txt
test/locale/src/main/webapp/WEB-INF/beans.xml
test/locale/src/main/webapp/WEB-INF/views/locale.jsp
test/locale/src/main/webapp/index.html
test/locale/src/main/webapp/ozark.css
test/locale/src/test/java/org/glassfish/ozark/test/locale/LocaleIT.java
test/pom.xml

Full implementation of this proposal:
https://github.com/mvc-spec/mvc-spec/pull/2

Implementation of MVC_SPEC-27 "Handling of Locale and Language"

---

ozark/src/main/java/org/glassfish/ozark/core/ViewResponseFilter.java
test/view-annotation/src/main/java/org/glassfish/ozark/test/view/HelloController.java
test/view-annotation/src/main/java/org/glassfish/ozark/test/view/MyApplication.java
test/view-annotation/src/main/webapp/WEB-INF/web.xml
test/view-annotation/src/main/webapp/error.html
test/view-annotation/src/main/webapp/index.html
test/view-annotation/src/test/java/org/glassfish/ozark/test/view/ViewAnnotationIT.java

Return the correct status code when using @View and throwing an Exception.
Fix for [OZARK-73](https://java.net/jira/browse/OZARK-73).

OZARK-73: Return the correct status code when using @View 

---

ozark/src/main/java/org/glassfish/ozark/binding/BindingInterceptorImpl.java
ozark/src/main/java/org/glassfish/ozark/binding/BindingResultUtils.java
ozark/src/main/java/org/glassfish/ozark/core/ViewResponseFilter.java
ozark/src/main/java/org/glassfish/ozark/locale/LocaleResolverChain.java
ozark/src/main/java/org/glassfish/ozark/security/CsrfValidateInterceptor.java
ozark/src/main/java/org/glassfish/ozark/util/AnnotationUtils.java
ozark/src/main/java/org/glassfish/ozark/util/PathUtils.java

Resolves [OZARK-83](https://java.net/jira/browse/OZARK-83).

OZARK-83: Fix PMD Errors

---

bin/test-integration-gf-docker.sh

Added a script for executing the integration-tests in a dockerized Glassfish.

Script for integration tests via docker

---

ext/thymeleaf/pom.xml
ext/thymeleaf/src/main/java/org/glassfish/ozark/ext/thymeleaf/DefaultTemplateEngineProducer.java

See [OZARK-84](https://java.net/jira/browse/OZARK-84)

OZARK-84 Upgrade Thymeleaf 3

---

ozark/src/main/java/org/glassfish/ozark/MvcContextImpl.java

Adds the API changes of [mvc-spec PR#7](https://github.com/mvc-spec/mvc-spec/pull/7).
(build will fail until mentioned spec PR is merged back to upstream)

MVC_SPEC-55: avoid hardcoding URIs in templates (not implemented yet)

---

test/application-path/src/main/webapp/index.html
test/book-cdi/src/main/webapp/index.html
test/book-models/src/main/webapp/index.html
test/conversation/src/main/webapp/index.html
test/csrf-property/src/main/webapp/index.html
test/csrf/src/main/webapp/index.html
test/events/src/main/webapp/index.html
test/exceptions/src/main/webapp/index.html
test/facelets/src/main/webapp/index.html
test/freemarker/src/main/webapp/index.html
test/handlebars/src/main/webapp/index.html
test/jade/src/main/webapp/index.html
test/mustache/src/main/webapp/index.html
test/mvc/src/main/webapp/index.html
test/produces/src/main/webapp/index.html
test/redirect/src/main/webapp/index.html
test/returns/src/main/webapp/index.html
test/stringtemplate/src/main/webapp/index.html
test/thymeleaf/src/main/webapp/index.html
test/velocity/src/main/webapp/index.html
test/view-annotation/src/main/webapp/index.html

The test applications contain some links to the source code. This PR fixes these links to point to the new GitHub URLs.

Fixed source code links in tests

---

ext/asciidoc/pom.xml
ext/freemarker/pom.xml
ext/freemarker/src/main/java/org/glassfish/ozark/ext/freemarker/DefaultConfigurationProducer.java
ext/handlebars/pom.xml
ext/handlebars/src/main/java/org/glassfish/ozark/ext/handlebars/HandlebarsViewEngine.java
ext/mustache/pom.xml
ext/thymeleaf/pom.xml
test/asciidoc/src/main/webapp/index.html
test/asciidoc/src/main/webapp/ozark.css

I did some upgrades from jar's to extensions.
Note for Freemarker.
- 2.3.26-incubating - http://freemarker.org/freemarkerdownload.html
- The new Configuration was deprecated = http://freemarker.org/docs/pgui_config_incompatible_improvements.html
{  },s.

Update Jar's Extensions.

---

.travis.yml
.travis/tests.sh

Reactivate integration tests as talked in #135

reactivate integration tests on glassfish

---

core/src/main/java/org/mvcspec/ozark/core/ViewResponseFilter.java
core/src/main/java/org/mvcspec/ozark/core/ViewableWriter.java
core/src/main/java/org/mvcspec/ozark/engine/ViewEngineFinder.java
core/src/main/java/org/mvcspec/ozark/engine/Viewable.java
core/src/test/java/org/mvcspec/ozark/core/ViewableWriterTest.java
test/produces/pom.xml
test/produces/src/main/java/org/mvcspec/ozark/test/produces/HelloController.java
test/returns/pom.xml
test/returns/src/main/java/org/mvcspec/ozark/test/returns/HelloController.java

This PR contains the required changes for Ozark regarding mvc-spec/mvc-spec#109.
Please note that the tests will fail until the spec PR is merged.

Moved Viewable class from the spec to Ozark

---

ext/jetbrick/pom.xml
ext/jetbrick/src/main/java/org/mvcspec/ozark/ext/jetbrick/JetbrickViewEngine.java
ext/jetbrick/src/main/resources/META-INF/beans.xml
ext/pom.xml
test/jetbrick/pom.xml
test/jetbrick/src/main/java/org/mvcspec/ozark/test/jetbrick/HelloController.java
test/jetbrick/src/main/java/org/mvcspec/ozark/test/jetbrick/MyApplication.java
test/jetbrick/src/main/webapp/WEB-INF/beans.xml
test/jetbrick/src/main/webapp/WEB-INF/views/hello.jetx
test/jetbrick/src/main/webapp/index.html
test/jetbrick/src/main/webapp/ozark.css
test/jetbrick/src/test/java/org/mvcspec/ozark/test/jetbrick/JetbrickIT.java
test/pom.xml

I found this template engine by browsing the sparkjava page.
This template is very similar to Velocity, so I found it interesting to have it in Ozark.
http://subchen.github.io/jetbrick-template/2x/overview.html
https://github.com/subchen/jetbrick-template-2x
Thanks.

Add Jetbrick View engine.

---

core/src/main/java/org/mvcspec/ozark/bootstrap/OzarkInitializer.java

Fixed NPE in case if ServletContext injection not works for particular JAX-RS implementation

Fixed NPE in case if ServletContext injection not works

---

core/src/main/java/org/mvcspec/ozark/bootstrap/DefaultConfigProvider.java
core/src/main/java/org/mvcspec/ozark/security/CsrfExceptionMapper.java
core/src/main/java/org/mvcspec/ozark/security/CsrfValidateInterceptor.java

This pull requests contains the required changes for supporting the new `javax.mvc.security.CsrfValidationException`. Please refer to mvc-spec/mvc-spec#82 for details.

Added support for CsrfValidationException (mvc-spec/mvc-spec#82)

---

core/src/main/java/org/mvcspec/ozark/bootstrap/OzarkCoreFeature.java
core/src/main/java/org/mvcspec/ozark/bootstrap/OzarkInitializer.java

Fix for an issue reported on the user list. Travis, test please.

Enforce Ozark bootstrapping only in server mode

---

core/src/main/java/org/mvcspec/ozark/binding/BindingResultImpl.java

This is a minimal change to return immutable Set/List to satisfy MVC Spec requirement

Modifying returned sets and lists to be immutable as defined in MVC Spec

---

test/validation-i18n/src/main/java/org/mvcspec/ozark/test/validation/MyApplication.java
test/validation-i18n/src/main/java/org/mvcspec/ozark/test/validation/ValidationController.java
test/validation/src/main/java/org/mvcspec/ozark/test/validation/FormController.java
test/validation/src/main/java/org/mvcspec/ozark/test/validation/FormControllerProperty.java
test/validation/src/main/java/org/mvcspec/ozark/test/validation/MyApplication.java

This PR remove the annotation @ValidationOnExection in tests the project .

remove annotation ValidationOnExecution.

---

core/src/main/java/org/mvcspec/ozark/binding/BindingErrorImpl.java
core/src/main/java/org/mvcspec/ozark/binding/convert/MvcConverterProvider.java

Implementation of the new method proposed in mvc-spec/mvc-spec#162.
Please note that the CI build will fail until the corresponding spec pull request gets merged.

Implementation of BindingError#getSubmittedValue

---

ext/groovy/pom.xml
ext/groovy/src/main/java/org/mvcspec/ozark/ext/groovy/GroovyViewEngine.java
ext/groovy/src/main/java/org/mvcspec/ozark/ext/groovy/MarkupTemplateEngineProducer.java
ext/groovy/src/main/resources/META-INF/beans.xml
ext/pom.xml
test/groovy/pom.xml
test/groovy/src/main/java/org/mvcspec/ozark/test/groovy/HelloController.java
test/groovy/src/main/java/org/mvcspec/ozark/test/groovy/MyApplication.java
test/groovy/src/main/webapp/WEB-INF/beans.xml
test/groovy/src/main/webapp/WEB-INF/views/hello.tpl
test/groovy/src/main/webapp/index.html
test/groovy/src/main/webapp/ozark.css
test/groovy/src/test/java/org/mvcspec/ozark/test/groovy/GroovyIT.java
test/pom.xml

- add a new View Egine - Groovy 
Reference - > http://docs.groovy-lang.org/next/html/documentation/template-engines.html

View engine groovy

---

core/src/main/java/org/mvcspec/ozark/core/ViewableWriter.java
core/src/main/java/org/mvcspec/ozark/engine/ViewEngineContextImpl.java
core/src/test/java/org/mvcspec/ozark/core/ViewableWriterTest.java
core/src/test/java/org/mvcspec/ozark/engine/ViewEngineContextImplTest.java

Added the new `getLocale()` to `ViewEngineContext`.

Implementation of ViewEngineContext#getLocale()

---

.travis/tests.sh
tck/pom.xml

A first try to update Wildfly and Liberty to their latest versions

Updated Wildfly and Liberty for TCK runner

---

core/src/main/java/org/mvcspec/ozark/servlet/OzarkServletContextListener.java

PR the reference to the issue #186 .

OzarkServletContextListener-small adjust.

---

tck/pom.xml

this PR is an update for a version  new of tomee .
with this version, he fix one  of  the issue in #169 .

update Tomee 7.0.4 to 7.0.5

---

core/src/main/java/org/mvcspec/ozark/security/CsrfProtectFilter.java
core/src/main/java/org/mvcspec/ozark/security/CsrfValidateInterceptor.java
test/csrf/src/main/java/org/mvcspec/ozark/test/csrf/CsrfController.java

Changes for Ozark required by mvc-spec/mvc-spec#190.
Please note that the tests will fail until the upstream pull request is merged.

Renamed CsrfValid annotation to CsrfProtected

---

core/src/main/java/org/mvcspec/ozark/binding/BindingResultImpl.java
core/src/main/java/org/mvcspec/ozark/binding/validate/ValidationInterceptor.java
test/validation-i18n/src/main/java/org/mvcspec/ozark/test/validation/ValidationController.java
test/validation/src/main/java/org/mvcspec/ozark/test/validation/FormController.java
test/validation/src/main/java/org/mvcspec/ozark/test/validation/FormControllerProperty.java

This pull requests contains the required changes for mvc-spec/mvc-spec#192.
Please do not merge this one before the upstream pull request is merged!

Updated implementation of the BindingResult interface

---

core/src/main/java/org/mvcspec/ozark/engine/ServletViewEngine.java

Possible workaround for #200....

Fixed NPE in ServletViewEngine on Liberty (#200)

---

tck/pom.xml

update to new version 7.1.0 : 
https://www.tomitribe.com/blog/tomee-an-overview-of-the-tomee-7-1-release/

update TomEE of 7.0.5 to 7.1.0

---

core/src/main/java/org/mvcspec/ozark/OzarkConfig.java
core/src/main/java/org/mvcspec/ozark/Properties.java
core/src/main/java/org/mvcspec/ozark/core/ViewResponseFilter.java
core/src/test/java/org/mvcspec/ozark/core/ViewResponseFilterTest.java
test/def-ext/pom.xml
test/def-ext/src/main/java/org/mvcspec/ozark/test/mvc/DefaultExtensionController.java
test/def-ext/src/main/java/org/mvcspec/ozark/test/mvc/MyApplication.java
test/def-ext/src/main/resources/LICENSE.txt
test/def-ext/src/main/webapp/WEB-INF/beans.xml
test/def-ext/src/main/webapp/WEB-INF/views/extension.jsp
test/def-ext/src/main/webapp/index.html
test/def-ext/src/main/webapp/ozark.css
test/def-ext/src/test/java/org/mvcspec/ozark/test/mvc/DefaultExtensionIT.java
test/pom.xml

See an issue https://github.com/mvc-spec/ozark/issues/151 for details.

Add support for a default file extension for view names

---

core/src/main/java/org/mvcspec/ozark/core/ViewResponseFilter.java
examples/def-ext/src/main/java/org/mvcspec/ozark/test/mvc/DefaultExtensionController.java
examples/def-ext/src/main/webapp/index.html
examples/def-ext/src/test/java/org/mvcspec/ozark/test/mvc/DefaultExtensionIT.java

fix extension to Viewable.
